apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thaddeus
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/SebastianCie/Thaddeus
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app-thaddeus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
